# Unique name for this workflow
name: Deploy main branch to production org

# Definition when the workflow should run
on:
    push:
      branches: [ main ]
      paths:
        - 'force-app/**'

# Jobs to be executed
jobs:
    deploy-branch-to-production-org:
      runs-on: ubuntu-latest
      container:
        image: salesforce/cli:latest-slim
      steps:
          - name: 'Checkout source code'
            uses: actions/checkout@v3
            with:
              fetch-depth: 0

          - name: 'Authenticate to Production Org'
            shell: bash
            run: |
                set -x
                echo ${{ secrets.SFDX_PRODUCTION_URL}} | sf org login sfdx-url -u -a=production

          - name: 'Deploy the entire branch to Integration org'
            run: sf project deploy start -d force-app/ --target-org production --test-level RunLocalTests -w 30 --json
