name: Deploy integration branch to integration and staging/uat orgs

on:
    push:
      branches: [ dev ]
      paths:
        - 'force-app/**'


jobs:
    deploy-branch-to-int-and-staging-orgs:
        runs-on: ubuntu-latest
        container:
          image: salesforce/cli:latest-slim
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: 'Authenticate to Integration Org'
              shell: bash
              run: |
                  set -x
                  echo ${{ secrets.SFDX_INTEGRATION_URL}} | sf org login sfdx-url -u -a=integration

            - name: 'Deploy the entire branch to Integration org'
              run: sf project deploy start -d force-app/ --target-org=vivek.chander@crunchyroll.com.crunchydev --test-level RunLocalTests -w 30 --json


            # - name: 'Authenticate to Staging Org'
            #   shell: bash
            #   run: |
            #       set -x
            #       echo ${{ secrets.SFDX_STAGING_URL}} | sf org login sfdx-url -u -a=staging

            # - name: 'Deploy the entire branch to Staging org'
            #   run: sf project deploy start -d force-app/ --target-org staging --test-level RunLocalTests -w 30 --json
